#!/bin/bash



#generate script for task 0. My name is Betty

echo "#!/bin/bash" > 0-iam_betty

echo "sudo betty" >> 0-iam_betty

chmod u+x 0-iam_betty

git add 0-iam_betty

git commit -m "add script tha switches the current user to user betty"



# generate the script for task 1. Who am I

echo "#!/bin/bash" > 1-who_am_i

echo "echo $USER" >> 1-who_am_i

chmod u+x 1-who_am_i

git add 1-who_am_i

git commit -m "add script that prints the effective username of the current user"



# generate the script for task 2. Groups

echo "#!/bin/bash" > 2-groups

echo "cat /etc/group" >> 2-groups

chmod u+x 2-groups

git add 2-groups

git commit -m "add script that prints all the groups the current user is part of"





# generate the script for task 3. New owner

echo "#!/bin/bash" > 3-new_owner

echo "chown betty hello" >> 3-new_owner

chmod u+x 3-new_owner

git add 3-new_owner

git commit -m "add script that changes the owner of the file hello to the user betty"



# generate the script for task 4. Empty!

echo "#!/bin/bash" > 4-empty

echo "touch hello" >> 4-empty

chmod u+x 4-empty

git add 4-empty

git commit -m "add script that  creates an empty file called hello"



# generate the script for task 5. Execute

echo "#!/bin/bash" > 5-execute

echo "chmod u+x hello" >> 5-execute

chmod u+x 5-execute

git add 5-execute

git commit -m "add script that adds execute permission to the owner of the file hello"





# generate the script for task 6. Multiple permissions

echo "#!/bin/bash" > 6-multiple_permissions

echo "chmod ug+x hello" >> 6-multiple_permissions

chmod u+x 6-multiple_permissions

git add 6-multiple_permissions

git commit -m "add script that adds execute permission to the owner and the group owner, and read permission to other users, to the file hello"



# generate the script for task 7. Everybody!

echo "#!/bin/bash" > 7-everybody

echo "chmod ugo+x hello" >> 7-everybody

chmod u+x 7-everybody

git add 7-everybody

git commit -m "add script that adds execution permission to the owner, the group owner and the other users, to the file hello"



# generate the script for task 8. James Bond

echo "#!/bin/bash" > 8-James_Bond

echo "chmod 007 hello" >> 8-James_Bond

chmod u+x 8-James_Bond

git add 8-James_Bond

git commit -m "add script that adds all permissions to other users and none to user and user group, to the file hello"



# generate the script for task 9. John Doe

echo "#!/bin/bash" > 9-John_Doe

echo "chmod 753 hello" >> 9-John_Doe

chmod u+x 9-John_Doe

git add 9-John_Doe

git commit -m "add script that sets all permissions to user, read an execution to user group and write and execution to others, to the file hello"



# generate the script for task 10. Look in the mirror

echo "#!/bin/bash" > 10-mirror_permissions

echo "chmod --reference=olleh hello" >> 10-mirror_permissions

chmod u+x 10-mirror_permissions

git add 10-mirror_permissions

git commit -m "add script that sets the permission mode of the file hello the same as olleh’s mode"



# generate the script for task 11. Directories

echo "#!/bin/bash" > 11-directories_permissions

echo "chmod a+x */" >> 11-directories_permissions

chmod u+x 11-directories_permissions

git add 11-directories_permissions

git commit -m "add script that adds execute permission to all subdirectories of the current directory for the owner, the group owner and all other users"



# generate the script for task 12. More directories

echo "#!/bin/bash" > 12-directory_permissions

echo "mkdir -m 751 my_dir" >> 12-directory_permissions

chmod u+x 12-directory_permissions

git add 12-directory_permissions

git commit -m "add script that creates a directory called my_dir with permissions 751 in the working directory"



# generate the script for task 13. Change group

echo "#!/bin/bash" > 13-change_group

echo "chgrp school hello" >> 13-change_group

chmod u+x 13-change_group

git add 13-change_group

git commit -m "add script that changes the group owner to school for the file hello"



# generate the script for task 14. Owner and group

echo "#!/bin/bash" > 100-change_owner_and_group

echo "chown vincent:staff *" >> 100-change_owner_and_group

chmod u+x 100-change_owner_and_group

git add 100-change_owner_and_group

git commit -m "add script that changes the  owner to vincent and the group owner to staff for all the files and directories in the working directory"



# generate the script for task 15. Symbolic links

echo "#!/bin/bash" > 101-symbolic_link_permissions

echo "chown -h vincent:staff _hello" >> 101-symbolic_link_permissions

chmod u+x 101-symbolic_link_permissions

git add 101-symbolic_link_permissions

git commit -m "add script that changes the owner and the group owner of _hello to vincent and staff respectively"



# generate the script for task 16. If only

echo "#!/bin/bash" > 102-if_only

echo "chown --from=guillaume betty hello" >> 102-if_only

chmod u+x 102-if_only

git add 102-if_only

git commit -m "add script that changes the owner of the file hello to betty only if it is owned by the user guillaume"



# generate the script for task 17. Star Wars

echo "#!/bin/bash" > 103-Star_Wars

echo "telnet towel.blinkenlights.nl" >> 103-Star_Wars

chmod u+x 103-Star_Wars

git add 103-Star_Wars

git commit -m "add script that cwill play the StarWars IV episode in the terminal"
