#!/bin/bash
echo "#!/bin/bash" > 8-firstdelete
echo "rm /tmp/my_first_directory/betty" >> 8-firstdelete

chmod u+x 8-firstdelete

echo "The 8-firstdelete script deletes the file <code>betty</code> in <code>/tmp/my_first_directory</code>" >> README.md

git add README.md 8-firstdelete

git commit -m "add 8-firstdelete script and updates the README"



echo "#!/bin/bash" > 9-firstdirdeletion

echo "rm -rf /tmp/my_first_directory" >> 9-firstdirdeletion

chmod u+x 9-firstdirdeletion

echo "The 9-firstdirdeleteion script deletes the directory <code>my_first_directory</code> that is in the <code>/tmp</code> directory." >> README.md

git add README.md 9-firstdirdeletion

git commit -m "add 9-firstdirdeletion script and updates the README"



echo "#!/bin/bash" > 10-back

echo "cd -" >> 10-back

chmod u+x 10-back

echo "The 10-back script changes the working directory to the previous one <code>(source ./10-back)</code>" >> README.md

git add README.md 10-back

git commit -m "add 10-back script and updates the README"



echo "#!/bin/bash" > 11-lists

echo "ls -la && ls -la .. && ls -la /boot" >> 11-lists

chmod u+x 11-lists

echo "The 11-lists script lists  all files (even ones with names beginning with a period character, which are normally hidden) in the current directory and the parent of the working directory and the <code>/boot</code> directory (in this order), in long format." >> README.md

git add README.md 11-lists

git commit -m "add 11-lists script and updates the README"



echo "#!/bin/bash" > 12-file_type

echo "file /tmp/iamafile" >> 12-file_type

chmod u+x 12-file_type

echo "The 12-file_type script prints the type of the file named <code>iamafile</code>. The file iamafile will be in the <code>/tmp</code> directory" >> README.md

git add README.md 12-file_type

git commit -m "add 12-file_type script and updates the README"



echo "#!/bin/bash" > 13-symbolic_link

echo "ln -s /bin/ls __ls__" >> 13-symbolic_link

chmod u+x 13-symbolic_link

echo "The 13-symbolic_link script creates a symbolic link to <code>/bin/ls</code>, named <code>__ls__</code>. The symbolic link should be created in the current working directory." >> README.md

git add README.md 13-symbolic_link

git commit -m "add 13-symbolic_link script and updates the README"



echo "#!/bin/bash" > 14-copy_html

echo "cp -u *.html destination" >> 14-copy_html

chmod u+x 14-copy_html

echo "The 14-copy_html script copies all the HTML files from the current working directory to the parent of the working directory, but only copy files that did not exist in the parent of the working directory or were newer than the versions in the parent of the working directory." >> README.md

git add README.md 14-copy_html

git commit -m "add 14-copy_html script and updates the README"
